/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.joao.tela.biblioteca;

import telas.CadastrarLivro;

/**
 *
 * @author João
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUser = new javax.swing.JMenu();
        jMenuItemProfile = new javax.swing.JMenuItem();
        jMenuItemNewRegister = new javax.swing.JMenuItem();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuBooks = new javax.swing.JMenu();
        jMenuItemBookRegister = new javax.swing.JMenuItem();
        jMenuItemSearch = new javax.swing.JMenuItem();
        jMenuItemBookList = new javax.swing.JMenuItem();
        jMenuOptions = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jMenuUser.setText("Usuário");
        jMenuUser.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenuUserAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jMenuItemProfile.setText("Ver perfil");
        jMenuUser.add(jMenuItemProfile);

        jMenuItemNewRegister.setText("Novo cadastro");
        jMenuUser.add(jMenuItemNewRegister);

        jMenuItemLogout.setText("Logout");
        jMenuUser.add(jMenuItemLogout);

        jMenuBar1.add(jMenuUser);

        jMenuBooks.setText("Livros");

        jMenuItemBookRegister.setText("Cadastrar ");
        jMenuItemBookRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBookRegisterActionPerformed(evt);
            }
        });
        jMenuBooks.add(jMenuItemBookRegister);

        jMenuItemSearch.setText("Buscar ");
        jMenuBooks.add(jMenuItemSearch);

        jMenuItemBookList.setText("Acervo");
        jMenuItemBookList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBookListActionPerformed(evt);
            }
        });
        jMenuBooks.add(jMenuItemBookList);

        jMenuBar1.add(jMenuBooks);

        jMenuOptions.setText("Opções");
        jMenuBar1.add(jMenuOptions);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuUserAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenuUserAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuUserAncestorAdded

    private void jMenuItemBookListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBookListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemBookListActionPerformed

    private void jMenuItemBookRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBookRegisterActionPerformed
        // TODO add your handling code here:
        CadastrarLivro cv = new CadastrarLivro();
        cv.setVisible(true);
    }//GEN-LAST:event_jMenuItemBookRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBooks;
    private javax.swing.JMenuItem jMenuItemBookList;
    private javax.swing.JMenuItem jMenuItemBookRegister;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemNewRegister;
    private javax.swing.JMenuItem jMenuItemProfile;
    private javax.swing.JMenuItem jMenuItemSearch;
    private javax.swing.JMenu jMenuOptions;
    private javax.swing.JMenu jMenuUser;
    // End of variables declaration//GEN-END:variables
}
